[package]
edition = "2021"
name = "try-rust"
version = "0.1.0"

[dependencies]
id-arena = "2.2.1"
inkwell = {git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"]}
parser = {path = "../parser"}
